#Database configuration

#Url for the database connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tempum_db?createDatabaseIfNotExist=true}

#Username for the database connection
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}

#Password for the database connection
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

#Hibernate configuration ORM configuration
#Dialect for MySQL database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CORS configuration
# Si existe la variable de entorno APP_CORS_ALLOWED_ORIGINS, usa su valor. Si no, usa http://localhost:5173 por defecto.
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

# JWT secret key configuration
app.jwt.secret=${JWT_SECRET_KEY:J8u#1m!S0ftw@r3_T3mpum_P4ssw0rd_2026_Secur3Key}